apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: first-vela-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: oamdev/hello-world
        ports:
         - port: 8000
           expose: true
      traits:
        - type: scaler
          properties:
            replicas: 1

#   - name: frontend
#     type: frontend
#     properties:
#       name: frontend
#       image: vfarcic/devops-toolkit-series
#     traits:
#     - type: autoscaler
#       properties:
#         min: 3
#     - type: ingress
#       properties:
#         domain: localhost
#         http:
#           "/": 80
